name: Publish Release

on:
  workflow_run:
    workflows: [ "Publish Conan branch package" ]
    branches: [ main ]
    types:
      - completed


concurrency:
  group: publish-release-${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-conan-branch-package:
    uses: dice-group/cpp-conan-release-reusable-workflow/.github/workflows/publish-release.yml@main
    with:
      public_artifactory: false
      os: ubuntu-22.04
      compiler: clang-14
      cmake-version: 3.22.6
      conan-version: 1.59
    secrets:
      CONAN_USER: ${{ secrets.CONAN_USER }}
      CONAN_PW: ${{ secrets.CONAN_PW }}
