name: Publish Conan branch package

on: [ push ]

concurrency:
  group: publish-conan-branch-package-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-release:
    uses: dice-group/cpp-conan-release-reusable-workflow/.github/workflows/publish-conan-branch-package.yml@feature/conan2
    with:
      public_artifactory: true
      os: ubuntu-22.04
      compiler: clang-15
      cmake-version: 3.22.6
      conan-version: 2.0.13
    secrets:
      CONAN_USER: ${{ secrets.CONAN_USER }}
      CONAN_PW: ${{ secrets.CONAN_PW }}
