name: Publish Release

on:
  workflow_run:
    workflows: [ "Publish Conan branch package" ]
    branches: [ main ]
    types:
      - completed


concurrency:
  group: publish-release-${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-release:
    uses: dice-group/cpp-conan-release-reusable-workflow/.github/workflows/publish-release.yml@v2.0.5
    with:
      public_artifactory: true
      os: ubuntu-24.04
      compiler: clang-19
      cmake-version: 3.24.0
      conan-version: 2.30.0
    secrets:
      CONAN_CICD_USERNAME: ${{ secrets.CONAN_CICD_USERNAME }}
      CONAN_CICD_PASSWORD: ${{ secrets.CONAN_CICD_PASSWORD }}
      CONAN_CICD_ENDPOINT: ${{ secrets.CONAN_CICD_ENDPOINT }}